PatchClass/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Teacher.views import lessonPlan,login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', lessonPlan,name="lessonPlan"),
    url(r'^login$', login,name="login"),
    url(r'^Teacher/', include('Teacher.urls', namespace="Teacher")),
    url(r'^User/', include('User.urls', namespace="User"))
]

Teacher/urls.py
'''
Created on Aug 16, 2020

@author: patch
'''
# -*- coding:utf-8 -*-

from django.conf.urls import include, url
from Teacher.views import *

urlpatterns = [

    # reg
    url(r'^editClass$', editClass,name='editClass'),
    url(r'^api_editClass$',api_editClass,name='api_editClass'),
    url(r'^lessonPlan$',lessonPlan,name='lessonPlan'),
    url(r'^lessonCheckin$',lessonCheckin,name='lessonCheckin'),
    url(r'^api_lessonCheckin$',api_lessonCheckin,name='api_lessonCheckin'),
    url(r'^courseList$', courseList,name='courseList'),
    url(r'^courseEdit$', courseEdit,name='courseEdit'),
    url(r'^api_courseEdit$',api_courseEdit,name='api_courseEdit'),
    url(r'^userCoursePlan$', userCoursePlan,name='userCoursePlan'),
    url(r'^userLessonSkill$', userLessonSkill,name='userLessonSkill'),
    url(r'^api_deleteLesson$',api_deleteLesson,name='api_deleteLesson'),
    url(r'^horse$', horse,name='horse'),
    url(r'^swipe$', swipe,name='swipe'),

    ]
app_name = 'Teacher'

User/urls.py
"""PatchClass URL Configuration


"""
from django.conf.urls import url,include
from User.views import *


urlpatterns = [
    url(r'^profile$', profile,name="profile"),
    url(r'^work$', work,name="work"),
    url(r'^userList$', userList,name="userList"),
    url(r'^userEdit$', userEdit,name="userEdit"),
    url(r'^api_userEdit$', api_userEdit,name="api_userEdit"),
    url(r'^userSkill$', userSkill,name="userSkill"),
    url(r'^index$', index,name="index"),
    url(r'^pay$', pay,name="pay"),
    url(r'^myRefers$', myRefers,name="myRefers"),
    url(r'^api_pay$', api_pay,name="api_pay"),
    url(r'^changePW$', changePW,name="changePW"),
    url(r'^api_changePW$', api_changePW,name="api_changePW")


]
app_name = 'User'

User/views.py
# -*- coding:utf-8 -*-
'''
Created on Aug 16, 2020

@author: patch
'''
import json,time,datetime
from Tool import constant,models,util
from django import forms
from django.views.decorators.csrf import  csrf_exempt
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from Tool.models import Teacher, Classroom, User,Lesson, Course, UserLesson,Contract
from mongoengine.queryset.visitor import Q
from django.utils.dateparse import parse_datetime

def index(request):
    return render(request, 'index.html', {})

def myRefers(request):
    login_user = util.checkCookie2(request)
    if not (login_user):
        return HttpResponseRedirect('/login')
    users = []
    try:
        users = User.objects.filter(referrer=login_user.id)
    except:
        err = 1
    return render(request, 'myRefers.html', {'login_user':login_user,'users':users})

def changePW(request):
    login_user = util.checkCookie2(request)
    if not (login_user):
        return HttpResponseRedirect('/login')
    return render(request, 'changePW.html', {'login_user':login_user})

@csrf_exempt
def api_changePW(request):
    userId = request.POST.get("userId")
    pw = request.POST.get("pw")
    res = {"error": 0, "msg": "OK"}
    try:
        u = User.objects.get(id=userId)
        u.pw = util.str2md5(pw)
        u.save()

    except Exception as e:

        res = {"error": 1, "msg": str(e)}

    return util.JSONResponse(json.dumps(res, ensure_ascii=False))

def userList(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')
    inClass = request.GET.get("inClass")
    paid = request.GET.get("paid")
    learned = request.GET.get("learned")

    status = request.GET.get("status")
    query = Q(status__gt=-1)
    title = u'全部'

    other = {'?inClass=1':u'在班学生','?learned=1':u'学过','?paid=1':u'付费'}

    if inClass == '1':
        title = u'在班学生'
        other = {'?':u'全部','?learned=1':u'学过','?paid=1':u'付费'}
        query = query&Q(inClass=1)
    if learned == '1':
        title = u'学过'
        other = {'?':u'全部','?inClass=1':u'在班学生','?paid=1':u'付费'}
        query = query&Q(lessons__gt=0)

    if paid == '1':
        title = u'付费'
        other = {'?':u'全部','?inClass=1':u'在班学生','?learned=1':u'学过'}
        query = query&Q(status=1)

    if inClass == '0':
        query = query&Q(inClass__ne=1)


    users = User.objects.filter(query)  # @UndefinedVariable

    temp = []
    for u in users:
        grade = getGrade(u.gradeOneYear)
        if grade:
            u.grade = str(grade)
        dateNow = util.getDateNow()
        try:
            days = (dateNow-u.birthday).days
            u.year = str(days/365)
        except:
            err = 1
        u.referrerName = ''
        if u.referrer:
            try:
                rr = User.objects.get(id=u.referrer)
                u.referrerName = rr.name
            except Exception, e:
                print(e)
                u.referrerName = ''

        temp.append(u)
    users = temp
    return render(request, 'userList.html', {"login_teacher":login_teacher,"users":users,
                                             "title":title,"other":other})

def pay(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')
    userId = request.GET.get("userId")

    user = None
    contracts = []
    contract = Contract()
    contractId = request.GET.get("contractId")
    try:
        user = User.objects.get(id=userId)
        grade = getGrade(user.gradeOneYear)
        if grade:
            user.grade = str(grade)
        contracts = Contract.objects.filter(user=user.id)
    except Exception as e:
        print(e)
        user = None
    try:
        contract = Contract.objects.get(id=contractId)
    except:
        contract = Contract()
    refs = None
    try:
        query = Q(isReferrer=1)&Q(id__ne=userId)
        refs = User.objects.filter(query)
    except:
        refs = None
    #return render(request, 'userEdit.html')
    return render(request, 'pay.html', {"login_teacher":login_teacher,
           "grades":constant.GRADE,"refs":refs,"user":user,"contracts":contracts,
           "contract":contract})

@csrf_exempt
def api_pay(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')

    payId = request.POST.get("payId")
    userId = request.POST.get("userId")
    payWay = request.POST.get("payWay")
    payTime = request.POST.get("payTime")
    validDate = request.POST.get("validDate")

    income = request.POST.get("income")
    refundTime = request.POST.get("refundTime")
    lesson = request.POST.get("lesson")
    refund = request.POST.get("refund")
    memo = request.POST.get("memo")
    if not payTime or payTime == '':
        res = {"error": 1, "msg": "no pay time"}
        return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    if not income or income == '':
        res = {"error": 1, "msg": "no pay amount"}
        return util.JSONResponse(json.dumps(res, ensure_ascii=False))

    ptime = None #交费之间
    vtime = None #课程结束时间
    rtime = None #退费时间
    status = 0
    isReferrer = 0
    try:
        ptime = util.local_to_utc(payTime+' 00:00:00',"Asia/Shanghai")
        status = 1
    except:
        res = {"error": 1, "msg": "pay time err"}
        return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    if refundTime and len(refundTime) > 1:
        try:
          rtime = util.local_to_utc(refundTime+' 00:00:00',"Asia/Shanghai")
          status = 2
        except:
          res = {"error": 1, "msg": "refund time err"}
          return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    try:
        vtime = util.local_to_utc(validDate+' 00:00:00',"Asia/Shanghai")
        status = 1
    except:
        err = 1
    inc = 0
    try:
        inc = int(income)
    except:
        res = {"error": 1, "msg": "pay amount number err"}
        return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    lessonAmount = 0
    try:
        lessonAmount = int(lesson)
    except:
        res = {"error": 1, "msg": "lesson amount err"}
        return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    referrer = None

    user = None
    try:
        user = User.objects.get(id=userId)  # @UndefinedVariable
    except:
        res = {"error": 1, "msg": "user not found err"}
        return util.JSONResponse(json.dumps(res, ensure_ascii=False))

    referrer = request.POST.get("referrer")
    try:
        ref = User.objects.get(id=referrer)  # @UndefinedVariable
    except:
        ref = None

    cont = None
    print('[payId--------------]')
    print(payId)
    if not payId or payId == '' or payId == 'None':
        print('[NO----payId--------------]')
        cont = Contract()
    else:
        try:
            cont = Contract.objects.get(id=payId)
        except:
            res = {"error": 1, "msg": "Contract ID err"}
            return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    cont.user = user
    cont.payTime = ptime
    cont.validDate = vtime
    cont.income = inc
    cont.lesson = lessonAmount
    cont.memo = memo
    cont.payWay = payWay

    if rtime:
        cont.refundTime = rtime
        status = 2
        if refund and refund != '':
            refu = 0
            try:
                refu = int(refund)
            except:
                res = {"error": 1, "msg": "refund amount number err"}
                return util.JSONResponse(json.dumps(res, ensure_ascii=False))
            cont.refund = refu

    cont.save()
    user.status = status
    #user.isReferrer = isReferrer
    if ref:
        user.referrer = str(ref.id)
    else:
        user.referrer = None

    user.save()

    res = {"error": 0, "msg": "OK"}
    return util.JSONResponse(json.dumps(res, ensure_ascii=False))

def userEdit(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')
    userId = request.GET.get("userId")
    user = None
    try:
        user = User.objects.get(id=userId)  # @UndefinedVariable
        grade = getGrade(user.gradeOneYear)
        if grade:
            user.grade = str(grade)

    except Exception as e:
        print('[user errrrrrrr]')
        print(e)
        user = User()
    temp = []
    refs = []
    try:
        query = Q(isReferrer=1)&Q(id__ne=userId)
        if not user.name:
            query = Q(isReferrer=1)
        refs = User.objects.filter(query)

    except Exception as e:
        print('[refs errrrrrrr]')
        print(e)
        refs = []
    #return render(request, 'userEdit.html')

    return render(request, 'userEdit.html', {"login_teacher":login_teacher,"grades":constant.GRADE,"refs":refs,"user":user})

@csrf_exempt
def api_userEdit(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')


    userId = request.POST.get("userId")
    name = request.POST.get("name")
    name2 = request.POST.get("name2")
    gender = request.POST.get("gender")
    grade = request.POST.get("grade")
    if not grade or grade == '':
        grade = ''

    birthdayStr = request.POST.get("birthday")
    birthday = None
    try:
        birthday = util.local_to_utc(birthdayStr + " 12:00:00","Asia/Shanghai")
    except:
        birthday = None
    location = request.POST.get("location")
    timezone = request.POST.get("timezone")
    customer1 = request.POST.get("customer1")
    c1tel = request.POST.get("c1tel")
    c1email =  request.POST.get("c1email")
    c1wechat = request.POST.get("c1wechat")
    statusStr  =  request.POST.get("status")
    gradeOneYear = getGradeOneYear(grade)
    referrer = None

    try:
        status = int(statusStr)
        print(status)

    except Exception as e:
        print(e)
        status = 0

User/templates/changePW.html
{% extends "base.html" %}
{%load filter%}
{% block content %}
<style>
  .h3p{width:100%;margin:10px 0 0 0 ;background-color:#eee;}
  .input{font-size:18px;padding:5px;}
  .inputTag{background:#dddddd;}
</style>
<div style="height:10px;"></div>
<div class="input">改密码</div>

<div class="input"><font class="inputTag">名字</font>&nbsp;{{login_user.name}}&nbsp;&nbsp;{{login_user.name2|default:''}}</div>



<div class="input">密码<input id="pw" type="password" /></div>
<div class="input">确认密码<input id="pw2" type="password" /></div>

<div  onclick="savepw()" style="padding:20px;text-align:center;"><button style="width:80%;height:40px;">Save</button>
{% endblock %}

{% block scripts %}
    <script>

        function savepw() {

          var pw = $("#pw").val();
          var pw2 = $("#pw2").val();
          if(pw!=pw2){
                alert('密码不一致！');
                return;
          }
          if(pw==''){
                alert('密码不能空！');
                return;
          }

            $.post("{% url 'User:api_changePW' %}", {
                "userId":'{{login_user.id}}',
                "pw": pw
            }, function (res) {
                alert(res["msg"]);
                if(res["error"]==0){
                    var url = "{% url 'User:myRefers' %}";
                    window.location.href = url;
                }

            });


        }

    </script>
{% endblock %}

User/templates/myRefers.html
{% extends "base.html" %}
{%load filter%}
{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.css">
<style>
  .container{background-color: #fff;}


  </style>

<div style="width:90%;">

<div style="float:right;font-size:20px;padding:5px;max-width:800px;min-width:500px;">
{{login_user.name}}    <a style="font-size:14px;" href="{% url 'User:changePW' %}">改密码></a>
</div>

</div>
<div style="clear:both;">
<table  id="datatable" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>序号</th><th>名字</th><th>性别</th><th>城市</th><th>年级</th><th>referrer</th><th>听课数</th><th>在班</th><th>付费</th>
  </tr>
  </thead>
  <tbody>
  {%for user in users%}
  <tr>
    <td></td>
    <td >
      {{user.name}}|{{user.name2|default:''}}
    </td>
    <td>{{user.gender|default:''}}</td>
    <td>{{user.location}}</td>
    <td>{{user.grade|default:""}}</td>
    <td>{{user.referrerName|default:""}}</td>
    <td><a target="_blank" href="{% url 'User:profile' %}?userId={{user.id}}">{{user.lessons|default:''}}</a></td>
    <td>{%if user.inClass == 1%}是{%endif%}</td>
    <td></td>
  </tr>
  {%endfor%}
  </tbody>
</table>
</div>




{% endblock %}

{% block scripts %}
<script>


  $(document).ready(function () {
    console.log($( document ).width());
    console.log($( window ).width());
    var wid = $( document ).width();
    $(".header").css("width",wid);
    wid = $( window ).width()/3*0.9;
    $(".week").css("width",wid);
    console.log(wid);
    var t = $('#datatable').DataTable({
        columnDefs: [
            {
                searchable: false,
                orderable: false,
                targets: 0,
            },
        ],
        order: [[1, 'asc']],
        "paging":   false,
        "searching": false,
        "info":false,

          dom: 'Bfrtip',
          buttons: [
            { extend: 'copy', text: '复制' },
            { extend: 'csv', text: '保存' },
            { extend: 'print', text: '打印' }
          ]
      });
      t.on('order.dt search.dt', function () {
              let i = 1;

              t.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
                  this.data(i++);
              });
          }).draw();

  });
  //$( ".block" ).animate({ "left": "-=70px" }, "fast" );


</script>
{% endblock %}

User/templates/pay.html
{% extends "base.html" %}
{%load filter%}
{% block content %}
{% load tz %}
{% localtime on %}

<style>
  .h3p{width:100%;margin:10px 0 0 0 ;background-color:#eee;}
  .input{font-size:18px;padding:5px;}
  .inputTag{background:#dddddd;}
</style>
<div style="height:10px;"></div>
<div class="input">付费</div>

<div class="input"><font class="inputTag">名字</font>&nbsp;{{user.name}}&nbsp;&nbsp;{{user.name2|default:''}}</div>

<div class="input">

    referrer&nbsp;<select id="referrer"><option value="0" selected>请选择</option>
        {%for ref in refs%}
      <option value="{{ref.id}}" {%if user.referrer == ref.id|stringformat:"s"%}selected{%endif%} >{{ref.name}}</option>
        {%endfor%}
    </select>
</div>

<div class="input">{{user.gender}}&nbsp;&nbsp;
    {%for s in grades%}
     {%if user.grade == s%}{{s|get_name:"grade"}}{%endif%}
    {%endfor%}
    &nbsp;{{user.location|default:''}}
</div>

<div class="input"><font class="inputTag">家长</font>&nbsp;{{user.customer1|default:''}}</div>
<div class="input"><font class="inputTag">电话</font>&nbsp;{{user.c1tel|default:''}}</div>
<div class="input"><font class="inputTag">微信</font>&nbsp;{{user.c1wechat|default:''}}</div>


<div class="input">缴费时间&nbsp;<input id="payTime" {%if contract.payTime %} value="{{contract.payTime|get_localtime:login_teacher.timezone}}" {%endif%} />
  方式<select id="payWay"><option value="wechat" {%if contract.payWay == 'wechat'%}selected{%endif%}>微信</option>
  <option value="alipay" {%if contract.payWay == 'alipay'%}selected{%endif%}>支付宝</option>
  <option value="bank" {%if contract.payWay == 'bank'%}selected{%endif%}>银行</option>
  <option value="other" {%if contract.payWay == 'other'%}selected{%endif%}>其他</option>
</select>
</div>
<div class="input">金额&nbsp;<input id="income"  value="{{contract.income|default:""}}"/>
<div class="input">课次&nbsp;<input id="lesson" value="{{contract.lesson|default:""}}"/>
<div class="input">截止时间&nbsp;<input id="validDate"  {%if contract.validDate %}value="{{contract.validDate|get_localtime:login_teacher.timezone}}" {%endif%} />
<div class="input">备注&nbsp;<input id="memo" value="{{contract.memo|default:""}}"/>
    <hr />
<div class="input">退款时间&nbsp;<input id="refundTime" />
<div class="input">退款金额&nbsp;<input id="refund" />

<div  onclick="savepay()" style="padding:20px;text-align:center;"><button style="width:80%;height:40px;">Save</button></div>

<div style="margin:20px 0 0 0;">
    交费记录
    {%for c in contracts%}
    <div><a href="{% url 'User:pay' %}?userId={{user.id}}&contractId={{c.id}}">{{c.payTime|get_localtime:login_teacher.timezone}} {{c.income}}元 [{{c.payWay}}] {{c.memo}}</a></div>
    {%endfor%}
</div>



{% endlocaltime %}

{% endblock %}

{% block scripts %}
    <script>

        function savepay() {

          var payTime = $("#payTime").val();
          var income = $("#income").val();
          if(payTime==''){
                alert('缴费时间不能空！');
                return;
          }
          if(income==''){
                alert('金额不能空！');
                return;
          }

            $.post("{% url 'User:api_pay' %}", {
                {%if contract%}"payId":'{{contract.id}}',{%endif%}
                "userId":'{{user.id}}',
                "payTime": payTime,
                "validDate": $("#validDate").val(),
                "income": income,
                "payWay": $("#payWay").val(),
                "memo": $("#memo").val(),
                "lesson": $("#lesson").val(),
                "lesson": $("#lesson").val(),
                "refundTime": $("#refundTime").val(),
                "refund": $("#refund").val(),
                "referrer": $("#referrer").val()

            }, function (res) {
                alert(res["msg"]);
                if(res["error"]==0){
                    var url = "{% url 'User:userList' %}";
                    window.location.href = url;
                }

            });


        }

    </script>
{% endblock %}

User/templates/profile.html
{% extends "base.html" %}
{%load filter%}
{% block content %}
<style>
  .greyBackground{background-color:#ddd;padding:3px;margin:0 0 10px 0;}
  .yellowBackground{background-color:yellow;padding:3px;margin:0 0 10px 0;}
</style>

{%if user%}
<div  style="width:100%;margin:0 auto;font-size:20px;text-align:center;padding:6px;">{{user.name}} 的成长记录</div>
{%if login_teacher%}<div>{{user.name2}} {{user.gender}} {{user.location}} {{user.birthday|date:"Y-m-d"}} 联系人：{{user.customer1}} (微信号：{{user.c1wechat}}）</div>

{%if user.isReferrer == 1%}
<tr>
    <td></td>
</tr>
{%endif%}

{%if classrooms%}<div style="padding-bottom:10px"><font class="yellowBackground">上课时间{%if user.timezone != 'Asia/Shanghai'%}({{user.timezone}}){%endif%}</font>{%endif%}
{%for classTime in classrooms%}
周{{classTime.lessonWeekday|week_name}}&nbsp;{{classTime.lessonTime}}&nbsp;|
{%endfor%}
</div>{%endif%}
{%if lessons%}<div style="text-align:center;font-weight:bold;"><a href="{% url 'User:userSkill' %}?userId={{user.id}}">→ {技能分布}</a></div>{%endif%}
<div>
  {%for l in lessons%}
  <br>

  【{{forloop.revcounter}}】
  {{l.lessonDate|date:"Y-m-d"}}&nbsp;{{l.lesson.course.name}}<br>
  <div style="width:100%;margin:0 auto;text-align:center;">
    {%if l.mediaType == 'video' %}
    <video width="320" height="240" controls poster="{{l.work}}">
      <source src="{{l.media}}" type="video/mp4">
    </video>
    {%endif%}
    {%if l.mediaType == 'image' %}
    <img src="{{l.media}}" style="width:100%;" />
    {%endif%}
  </div>
  <p class="greyBackground" style="margin:0 0 10px 0;">{{l.lesson.course.content}}</p>
  {%if l.memo%}{%if l.memo != 'None' %}<p><font class="greyBackground">课堂观察</font>&nbsp;{{l.memo}}{%endif%}{%endif%}
  <p><font class="greyBackground">主题</font>&nbsp;{%for s in l.theme%}{{s|get_name:"theme"}}&nbsp;{%endfor%}</p>
  <p><font class="greyBackground">技术</font>&nbsp;{%for s in l.skill%}{{s|get_name:"skill"}}&nbsp;{%endfor%}</p>
  <p><font class="greyBackground">能力</font>&nbsp;{%for s in l.ability%}{{s|get_name:"ability"}}&nbsp;{%endfor%}</p>


  {%endfor%}

  {%else%}
  <div style="width:100%;text-align:center;padding:20px;font-size:16px;">
  请输入学生小名或英文名
  <p><input id="name" name="name" /></p>
  <p><button onclick="go()">查询学习记录</button></p>
  </div>

  {%endif%}
  <div style="height:20px;"></div>
  <hr>
  <div style="width:100%;text-align:center;font-size:16px;"><a href="https://mp.weixin.qq.com/s/TJi0vnCjJth4mpxBgorraQ">如何加入Patch老师的Scratch编程小课程？</a>
  </div>
  <div style="padding:0px;width:100%;text-align:center"><img src="/static/img/mylogo2.png" style="width:50%" /></div>
{% endblock %}

{% block scripts %}

<script>
  $(document).ready(function() {

      $("title").html("{{user.name}}的Scratch课堂成长记录")
  })
  function goWork(uid,lid){
    var para = "?userId="+uid+"&lessonId="+lid;
    document.location.href="{% url 'User:work' %}"+para;
  }
  function go(){

    document.location.href="{% url 'User:profile' %}?name="+$("#name").val()
  }
</script>

{% endblock %}

User/templates/userList.html
{% extends "base.html" %}
{%load filter%}
{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.css">
<style>
  .container{background-color: #fff;}


  </style>

<div style="width:90%;">

<div style="float:left;font-size:20px;padding:5px;max-width:500px;min-width:200px;"><a style="font-size:14px;" href="{% url 'Teacher:lessonPlan' %}">Home></a>
  &nbsp;{{title}}&nbsp;
  <font style="font-size:14px;">{%for key,value in other.items%}&nbsp;<a href="{% url 'User:userList' %}{{key}}">{{value}}</a>{%endfor%}</font>
</div>
<div style="float:right:margin:10px;padding:5px;">&nbsp;&nbsp;
  <button><a href="{% url 'User:userEdit' %}">add new user</a></button>
</div>
</div>
<div style="clear:both;">
<table  id="datatable" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>序号</th><th>名字</th><th>性别</th><th>城市</th><th>年级</th><th>referrer</th><th>听课数</th><th>在班</th><th>付费</th>
  </tr>
  </thead>
  <tbody>
  {%for user in users%}
  <tr>
    <td></td>
    <td >
      <a href="{% url 'User:userEdit' %}?userId={{user.id}}">
      {{user.name}}|{{user.name2|default:''}}</a>
    </td>
    <td>{{user.gender|default:''}}</td>
    <td>{{user.location}}</td>
    <td>{{user.grade|default:""}}</td>
    <td>{{user.referrerName|default:""}}</td>
    <td><a target="_blank" href="{% url 'User:profile' %}?userId={{user.id}}">{{user.lessons|default:''}}</a></td>
    <td>{%if user.inClass == 1%}是{%endif%}</td>
    <td><button class="payButton" id="{{user.id}}" {% if user.status == 1 %}style="background-color: #4CAF50;"{%endif%}">{{user.status}}-{{user.name}}</button>
  </tr>
  {%endfor%}
  </tbody>
</table>
</div>
<div style="padding:10px;">
  <button><a href="{% url 'User:userEdit' %}">add new user</a></button>
</div>




{% endblock %}

{% block scripts %}
<script>


  $(document).ready(function () {
    console.log($( document ).width());
    console.log($( window ).width());
    var wid = $( document ).width();
    $(".header").css("width",wid);
    wid = $( window ).width()/3*0.9;
    $(".week").css("width",wid);
    console.log(wid);
    var t = $('#datatable').DataTable({
        columnDefs: [
            {
                searchable: false,
                orderable: false,
                targets: 0,
            },
        ],
        order: [[1, 'asc']],
        "paging":   false,
        "searching": false,
        "info":false,

          dom: 'Bfrtip',
          buttons: [
            { extend: 'copy', text: '复制' },
            { extend: 'csv', text: '保存' },
            { extend: 'print', text: '打印' }
          ]
      });
      t.on('order.dt search.dt', function () {
              let i = 1;

              t.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
                  this.data(i++);
              });
          }).draw();

  });
  //$( ".block" ).animate({ "left": "-=70px" }, "fast" );

function goUser(userId){
  var para = "?userId="+userId
  document.location.href="{% url 'User:userEdit' %}"+para
}
$(".payButton").click(function(){
    console.log('-----------click-----------')
    var para = "?userId="+$(this).attr("id")
    document.location.href="{% url 'User:pay' %}"+para
});

</script>
{% endblock %}