PatchClass/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Teacher.views import lessonPlan,login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', lessonPlan,name="lessonPlan"),
    url(r'^login$', login,name="login"),
    url(r'^Teacher/', include('Teacher.urls', namespace="Teacher")),
    url(r'^User/', include('User.urls', namespace="User"))
]

Teacher/urls.py
'''
Created on Aug 16, 2020

@author: patch
'''
# -*- coding:utf-8 -*-

from django.conf.urls import include, url
from Teacher.views import *

urlpatterns = [

    # reg
    url(r'^editClass$', editClass,name='editClass'),
    url(r'^api_editClass$',api_editClass,name='api_editClass'),
    url(r'^lessonPlan$',lessonPlan,name='lessonPlan'),
    url(r'^lessonCheckin$',lessonCheckin,name='lessonCheckin'),
    url(r'^api_lessonCheckin$',api_lessonCheckin,name='api_lessonCheckin'),
    url(r'^courseList$', courseList,name='courseList'),
    url(r'^courseEdit$', courseEdit,name='courseEdit'),
    url(r'^api_courseEdit$',api_courseEdit,name='api_courseEdit'),
    url(r'^userCoursePlan$', userCoursePlan,name='userCoursePlan'),
    url(r'^userLessonSkill$', userLessonSkill,name='userLessonSkill'),
    url(r'^api_deleteLesson$',api_deleteLesson,name='api_deleteLesson'),
    url(r'^horse$', horse,name='horse'),
    url(r'^swipe$', swipe,name='swipe'),

    ]
app_name = 'Teacher'

User/urls.py
"""PatchClass URL Configuration


"""
from django.conf.urls import url,include
from User.views import *


urlpatterns = [
    url(r'^profile$', profile,name="profile"),
    url(r'^work$', work,name="work"),
    url(r'^userList$', userList,name="userList"),
    url(r'^userEdit$', userEdit,name="userEdit"),
    url(r'^api_userEdit$', api_userEdit,name="api_userEdit"),
    url(r'^userSkill$', userSkill,name="userSkill"),
    url(r'^index$', index,name="index"),
    url(r'^pay$', pay,name="pay"),
    url(r'^myRefers$', myRefers,name="myRefers"),
    url(r'^api_pay$', api_pay,name="api_pay"),
    url(r'^changePW$', changePW,name="changePW"),
    url(r'^api_changePW$', api_changePW,name="api_changePW")


]
app_name = 'User'

Teacher/views.py
# -*- coding:utf-8 -*-
'''
Created on Aug 16, 2020

@author: patch
'''
import json,time,datetime
from Tool import constant,models,util, batch
from django import forms
from django.views.decorators.csrf import  csrf_exempt
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render#,render_to_response
from django.utils.dateparse import parse_datetime
from Tool.models import Teacher, Classroom, User,Lesson, Course, UserLesson
from mongoengine.queryset.visitor import Q

# Create your views here.

def swipe(request):
    login_teacher = util.checkCookie(request)
    id = request.GET.get('id')
    if not id == 'patch':
        return HttpResponseRedirect('/login')
    page = request.GET.get('page')
    return render(request, 'swipe.html', {"page":page})

def horse(request):
    login_teacher = util.checkCookie(request)
    id = request.GET.get('id')
    if not id == 'patch':
        return HttpResponseRedirect('/login')
    page = request.GET.get('page')
    return render(request, 'horse.html', {"page":page})

class UserLoginForm(forms.Form):
    username = forms.CharField(label='登录名', max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control','autofocus':'autofocus'}))
    password = forms.CharField(label='密码', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

@csrf_exempt
def login(request):
    isTeacher = False
    if request.method == "POST":
        uf = UserLoginForm(request.POST)

        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            openId = request.POST.get("openId")


            res = {"error": 0, "msg": "OK"}
            password_md5 = util.str2md5(password)

            if password_md5 == None:
                res = {"error": 1, "msg": "非法字符"}
            #username = username.lower()

            user = None

            users = []
            users = Teacher.objects.filter(login__exact=username).filter(pw__exact=password_md5)  # @UndefinedVariable
            try:
                user = users.first()
                if user.status == -1:
                    res = {"error": 1, "msg": "已离职"}
                else:
                    isTeacher = True
            except:
                users = User.objects.filter(login=username).filter(pw=password_md5)  # @UndefinedVariable
                try:
                    user = users.first()
                    if user.status == -1:
                        res = {"error": 1, "msg": "已注销"}
                except Exception as e:
                    res = {"error": 1, "msg": "用户名密码错误"}


            res_login = res
            print('[isTeacher login------------------]')
            print(isTeacher)
            if res_login["error"] == 0 and isTeacher:

                response = HttpResponseRedirect('/Teacher/lessonPlan')
                response.set_cookie('isTeacher', '1')
                response.set_cookie('login', user.login.lower())
                response.set_cookie('userid', user.id)
                response.set_cookie('name', user.name)
                response.set_cookie('name2', user.name2)
                response.set_cookie('wechat',user.wechat)
                response.set_cookie('tel',user.tel)
                response.set_cookie('timezone',user.timezone)

                return response
            elif res_login["error"] == 0:
                response = HttpResponseRedirect('/User/myRefers')
                response.set_cookie('isTeacher', '0')
                response.set_cookie('login',user.login)
                response.set_cookie('userid', user.id)
                response.set_cookie('name', user.name)
                response.set_cookie('name2', user.name2)
                response.set_cookie('wechat',user.wechat)
                response.set_cookie('tel',user.tel)
                response.set_cookie('timezone',user.timezone)
                return response
            else:
                response = HttpResponseRedirect('/login?wrongLogin=1')
                return response
                #return render('login.html', {'msg': res_login["msg"], 'uf': uf})
    else:
        uf = UserLoginForm()
    return render(request, 'login.html', {'uf': uf,'addr':request.META['HTTP_HOST']})

def editClass(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')
    classroom = None
    classroomId = request.GET.get('classroomId')
    try:
        classroom = Classroom.objects.get(id=classroomId)  # @UndefinedVariable
    except:
        classroom = Classroom()

    query = Q(status__gt=0)
    if classroom:
        for u in classroom.users:
            query = query&Q(id__ne=u.id)
    #除了本班学生以外所有可选学生
    students = User.objects.filter(query).order_by('name')  # @UndefinedVariable

    classStudents = None
    if classroom:
        classStudents = classroom.users
    week_list = range(1, 8)
    teachers = Teacher.objects.all()  # @UndefinedVariable
    lans = constant.LAN

    return render(request, 'editClass.html', {"login_teacher":login_teacher,"classroom":classroom,
                                              "students":students,"classStudents":classStudents,
                                              'week_list':week_list,"teachers":teachers,"lans":lans,
                                              "searchDay":request.GET.get("searchDay")})
@csrf_exempt
def api_editClass(request):
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')

    classroomId = request.POST.get('classroomId')
    studentIds = request.POST.get('studentIds')
    teacherId = request.POST.get('teacherId')
    lan = request.POST.get('lan')
    lessonWeekday = request.POST.get('lessonWeekday')
    lessonTime = request.POST.get('lessonTime')

    res = {"error": 0, "msg": "OK"}
    classroom = None
    try:
        classroom = Classroom.objects.get(id=classroomId)  # @UndefinedVariable
    except Exception as e:
        print(e)
        classroom = None

    if not classroom:
        classroom = Classroom()
    teacher = None
    try:
        teacher = Teacher.objects.get(id=teacherId)  # @UndefinedVariable
    except:
        teacher = None

    classroom.teacher = teacher
    classroom.lan = lan
    classroom.lessonWeekday = lessonWeekday
    classroom.lessonTime = lessonTime

    students = []
    student_oid_list = json.loads(studentIds)
    for student_oid in student_oid_list:
        try:
            student = User.objects.get(id=student_oid)  # @UndefinedVariable
            student.inClass = 1
            student.save()
            students.append(student)
        except Exception as e:
            print(e)
            res = {"error": 1, "msg": str(e)}
            return util.JSONResponse(json.dumps(res, ensure_ascii=False))
    oldclass = classroom.users
    classroom.users = students
    classroom.save()
    for o in oldclass:
        stillIn = False
        for s in students:
            if o.id == s.id:
                stillIn = True
                break;
        if not stillIn:
            query = Q(users__contains=o.id)
            has = Classroom.objects.filter(query)  # @UndefinedVariable
            if len(has) == 0:
                o.inClass = 0
                o.save()

    return util.JSONResponse(json.dumps(res, ensure_ascii=False))


#展示一周每天课程安排，左右滑动展示前后一天
def lessonPlan(request):
    #batch.changeThemeToList()
    login_teacher = util.checkCookie(request)
    if not (login_teacher):
        return HttpResponseRedirect('/login')
    searchDayStr = request.GET.get("searchDay")
    searchDay = None
    try:
        searchDay = datetime.datetime.strptime(searchDayStr,"%Y%m%d")
    except:
        searchDay = None

    begin,end,last,next = util.getWeekFirstDay(searchDay)
    end = end.replace(hour=23)
    end = end.replace(minute=59)
    end = end.replace(second=59)
    isThisWeek = True

    #query = Q(teacher=login_teacher.id)&Q(users__ne=None)
    query = Q(teacher=login_teacher.id)
    lessonPlans = Classroom.objects.filter(query).order_by('lessonWeekday','lessonTime')  # @UndefinedVariable
    all = []

    lastDay = None
    temp = []
    i = 0
    date = None
    #courses = util.userCoursePlan(1)
    for c in lessonPlans:
        if lastDay != c.lessonWeekday:
            date = begin + datetime.timedelta(days=i)
            strd = datetime.datetime.strftime(date,"%Y-%m-%d")
            date = parse_datetime(strd + "T" + c.lessonTime + ":0+08:00")
            #date = parse_datetime('2020-09-19T10:00:0+08:00')

            i = i + 1
            try:
                if temp and len(temp) >0:
                    all.append(temp)
                    temp = []
            except Exception as e:
                print(e)
            lastDay = c.lessonWeekday
        c.date = date#util.utc_to_local(date, None)

        lesson = None
        extra = []
        try:
            query = Q(classroom=c.id)&Q(lessonDate__gte=begin)&Q(lessonDate__lte=end)
            lessons = Lesson.objects.filter(query)  # @UndefinedVariable
            if len(lessons) > 0:
                lesson = lessons[0]
                lesson.lessonDate = util.utc_to_local(lesson.lessonDate, None)
            c.lesson = lesson
            try:
                query = Q(lesson=lesson.id)
                userLessons = UserLesson.objects.filter(query)
                c.userLessons = userLessons
                for ul in userLessons:
                    has = 0
                    for u in c.users:
                        if u.id == ul.user.id:
                            has = 1
                            break
                    if has == 0:
                        extra.append(ul.user)
                c.extra = extra
            except Exception as e:
                print(e)
                c.userLessons = []
        except Exception as e:
            print(e)

Teacher/templates/courseList.html
{% extends "base.html" %}
{%load filter%}
{% block content %}

<style>
  .container{background-color: #fff;}


  </style>
<div style="height:10px;"></div>
<div style="font-size:20px;padding:5px;"><a style="font-size:14px;" href="{% url 'Teacher:lessonPlan' %}">Home></a>&nbsp;全部课程</div>
{%for courses in list%}
<div>
  {%for course in courses%}
{% if forloop.counter == 1%}
{{course.lan|get_name:'lan'}} {{course.level}}<br>
{%endif%}
<span style="padding:8px 0 0px 5px;">
{{forloop.counter}}·<a href="{% url 'Teacher:courseEdit' %}?courseId={{course.id}}">{{course.name}}</a>
</span>
  {%endfor%}
  </div>

{%endfor%}

<div style="padding:10px;">
  <button><a href="{% url 'Teacher:courseEdit' %}">add new course</a></button>
  <button><a target="_blank" href="{% url 'Teacher:userLessonSkill' %}">skill deploy</a></button>
</div>

{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function () {
    console.log($( document ).width());
    console.log($( window ).width());
    var wid = $( document ).width();
    $(".header").css("width",wid);
    wid = $( window ).width()/3*0.9;
    $(".week").css("width",wid);

  });
  //$( ".block" ).animate({ "left": "-=70px" }, "fast" );


function goCourse(courseId){
  var para = "?courseId="+courseId
  document.location.href="{% url 'Teacher:courseEdit' %}"+para
}
</script>
{% endblock %}

Teacher/templates/lessonCheckin.html
{% extends "base.html" %}
{%load filter%}
{% load tz %}
{% block content %}
{% localtime on %}
{% timezone "Asia/Shanghai" %}
  <style>

  body{

    background-color: #fff;margin:0;padding:0;width:100%;
  }
  .left{float:left;padding-top:6px;}
  .right{float:right;padding-right:10px;}
  .i{font-weight:bold;font-style: italic;}
  .bold_blue{font-weight:bold;color:blue;}
  </style>
<div style="padding-top:10px;">
  {{lessonDate}}
  {%if lesson%}<div>{{lesson.lessonDate|date:'n月j日'}} | <button onclick="deleteLesson()">删除</button> </div>{%endif%}
<div>
本课内容
<select id="courseId" onchange="changeCourse()">
  {%if not course%}<option selected>选择课程</option>{%endif%}
{%for c in courses%}
<option value="{{c.id}}" {%if c.id == course.id%}selected=selected{%endif%}>{{c.name}}</option>
{%endfor%}
</select>
<p id="courseContent" style="padding-top:6px;"><pre>{%if course%}{{course.content}}{%endif%}</pre></p>
</div>
{%if users%}
<div style="">
  课堂记录<textarea id="memo" rows="4" cols="80">{{lesson.memo|default:""}}</textarea>
  <input type="checkbox" id="checkAll"/>全选
</div>
{%endif%}
{%for student in users%}
<div>
<div class="left"><font class="bold_blue">{{student.name}}</font></div>
<div class="right">出勤&nbsp;<input type="checkbox" name="userId" value="{{student.id}}" {%if student.lesson%}checked{%endif%}/></div>
<div style="clear:both;width:97%;background-color:#eeeeee;padding:6px;">
  <p><font class="i">theme:</font> {%for s in course.theme%}{{ s|get_name:"theme" }}<input type="checkbox" name="{{student.id}}_theme" value="{{s}}" {%for ls in student.lesson.theme%} {%if ls == s%}checked{%endif%}{%endfor%} />&nbsp;{%endfor%}</p>
  <p><font class="i">extention:</font> {%for s in course.extention%}{{ s|get_name:"extention" }}<input type="checkbox" name="{{student.id}}_extention" value="{{s}}" {%for ls in student.lesson.extention%} {%if ls == s%}checked{%endif%}{%endfor%} />&nbsp;{%endfor%}</p>
  <p><font class="i">skill:</font> {%for s in course.skill%}{{ s|get_name:"skill" }}<input type="checkbox" name="{{student.id}}_skill" value="{{s}}" {%for ls in student.lesson.skill%} {%if ls == s%}checked{%endif%}{%endfor%} />&nbsp;{%endfor%}</p>
  <p><font class="i">ability:</font> {%for a in course.ability%}{{ a|get_name:"ability" }}<input type="checkbox" name="{{student.id}}_ability" value="{{a}}" {%for ls in student.lesson.ability%} {%if ls == a%}checked{%endif%}{%endfor%} />&nbsp;{%endfor%}</p>
  <p><font class="i">作品:</font><input type="text" id="{{student.id}}_work" value="{%if student.lesson.work%}{{student.lesson.work}}{%endif%}"/></p>
  <p><font class="i">展示:</font><input type="text" id="{{student.id}}_media" value="{%if student.lesson.media%}{{student.lesson.media}}{%endif%}"/></p>
  <p><font class="i">备忘:</font><textarea id="{{student.id}}_memo" style="width:90%;max-width:400px;">{{student.lesson.memo|default:""}}</textarea></p>
  </div>
</div>
{%endfor%}

<button onclick="checkin()">保存</button>

<div style="height:200px;"></div>
{% endtimezone %}
{% endlocaltime %}

{% endblock %}

{% block scripts %}
<script>

    $('#checkAll').click(function() {
        $("input[type=checkbox]").prop('checked',this.checked);
    });

  function changeCourse(){

    var courseId = $("#courseId").val();
    var para = "?classroomId={{classroom.id}}&lessonDate={{lessonDate}}&courseId="+courseId
    {%if lesson%}
      para = para + "&lessonId={{lesson.id}}"
    {%endif%}

    document.location.href="{% url 'Teacher:lessonCheckin' %}"+para
  }

function deleteLesson(){
  $.post("{% url 'Teacher:api_deleteLesson' %}", {

      "csrfmiddlewaretoken": "{{ csrf_token }}",
      "lessonId":"{{lesson.id}}"

  }, function (res) {
      if (res["error"] == 0) {
          alert("成功");
          var url = "{% url 'Teacher:lessonPlan' %}";
          window.location.href = url;
      } else {
          alert("失败:" + res["msg"])
      }
  });
}

function checkin(){

  var userID = [];//定义一个空数组
  $("input[name='userId']:checked").each(function(i){//把所有被选中的复选框的值存入数组
      userID[i] =$(this).val();
  });
  console.log(userID);

  var skill = ''
  for(var ii = 0;ii<userID.length;ii++){
    skill = skill + ';' + userID[ii]+',';//定义一个空数组
    $("input[name='"+userID[ii]+"_theme']:checked").each(function(i){//把所有被选中的复选框的值存入数组
          skill = skill + "_" + $(this).val();
    });
    skill = skill + ',';
    $("input[name='"+userID[ii]+"_extention']:checked").each(function(i){//把所有被选中的复选框的值存入数组
          skill = skill + "_" + $(this).val();
    });
    skill = skill + ',';
    $("input[name='"+userID[ii]+"_skill']:checked").each(function(i){//把所有被选中的复选框的值存入数组
          skill = skill + "_" + $(this).val();
    });
    skill = skill + ',';
    $("input[name='"+userID[ii]+"_ability']:checked").each(function(i){//把所有被选中的复选框的值存入数组
          skill = skill + "_" + $(this).val();
    });
    skill = skill + ',';
    skill = skill + $("#"+userID[ii]+"_work").val();
    skill = skill + ',';
    skill = skill + $("#"+userID[ii]+"_memo").val();
    skill = skill + ',';
    skill = skill + $("#"+userID[ii]+"_media").val();
  }

  console.log(skill);

  $.post("{% url 'Teacher:api_lessonCheckin' %}", {

      "csrfmiddlewaretoken": "{{ csrf_token }}",
      "lessonId":"{{lesson.id}}",
      "courseId":$("#courseId").val(),
      "lessonDate":'{{lessonDate}}',
      "classroomId":'{{classroom.id}}',
      "memo":$("#memo").val(),
      "data": skill

  }, function (res) {
      if (res["error"] == 0) {
          alert("成功");
          var url = "{% url 'Teacher:lessonPlan' %}"+"?searchDay={{searchDay}}";
          window.location.href = url;
      } else {
          alert("失败:" + res["msg"])
      }
  });
}


</script>
{% endblock %}

Teacher/templates/lessonPlan.html
{% extends "base.html" %}
{%load filter%}
{% load tz %}
{% block content %}

<style>
  .container{background-color: #fff;}
  body{
    background-color: #fff;margin:0;padding:0;width:100%;

  }
  .block {
    float:left;
    position: relative;
    background-color: rgb(145,218,255);
    left: 0px;
    width:170px;
    padding: 5px;
    margin-left: 1px;
    border-style: solid;
    border-color: #FFB600;
  }

  </style>

  <div class="week" style="float:left;padding:5px;">

  </div>

  <div class="week" style="line-height:20px;vertical-align:top;width:100%;float:left;text-align:center;font-size:20px;font-family:Arial;">
    <a style="font-size:14px;" href="{% url 'Teacher:lessonPlan' %}?searchDay={{last|date:'Ymd'}}">&#8678; 上一周</a>&nbsp;&nbsp;课 表&nbsp;&nbsp;<a style="font-size:14px;" href="{% url 'Teacher:lessonPlan' %}?searchDay={{next|date:'Ymd'}}">下一周 &#8680;</a></div>





<div style="clear:both;"></div>
<div style="width:1200px;position: absolute;top:76px;">
  {% for dayplans in lessonPlans %}
  <div class="block" >
  {%for plan in dayplans%}
  <div onclick="goClass('{{plan.id}}')">
  周{{plan.lessonWeekday|week_name}}

  {% localtime on %}
  {% timezone "Asia/Shanghai" %}

   {{plan.lessonTime}}&nbsp;&nbsp;(<font style="color:white;font-weight:bold;">{%if plan.lesson %}{{plan.lesson.lessonDate|date:"n月j日"}}{%else%}{{plan.date|date:"n月j日"}}{%endif%}</font>)
</div>

<div>{{plan.lan|get_name:'lan'}}</div>


  <p onclick="goCheckin('{{plan.id}}','{{plan.lesson.id}}','{{plan.date|date:"Y-m-d"}}T{{plan.date|date:"H:i"}}')" style="cursor:pointer;background-color:white;">{%if plan.lesson %}{<b>{{plan.lesson.course.name}}</b>}{%else%}&nbsp;{%endif%}</p>
  {% endtimezone %}
  {% endlocaltime %}
  <p>{%for u in plan.users%}<a href="javascript:goUser('{{u.id}}')">{%for ul in plan.userLessons%}{%if ul.user.id == u.id%}<font style="color:rgb(209,1,141);">{%endif%}{%endfor%}{{u.name}}{%for ul in plan.userLessons%}{%if ul.user.id == u.id%}</font>{%endif%}{%endfor%}</a>&nbsp;{%if forloop.counter == 3%}<br>{%endif%}{% endfor %}
     {%for ex in plan.extra%}<a href="javascript:goUser('{{ex.id}}')"><font style="color:rgb(209,1,141);">{{ex.name}}</font></a>&nbsp;{%endfor%}
  </p>

  {%endfor%}
  </div>
{% endfor %}


</div>


<div style='position:fixed;bottom:0;padding:10px;'><a href="{% url 'Teacher:courseList' %}">courseList</a> | <a href="{% url 'User:userList' %}">userList</a></div>

{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function () {
    console.log($( document ).width());
    console.log($( window ).width());
    var wid = $( document ).width();
    $(".header").css("width",wid);
    wid = $( window ).width()/3*0.9;
    //$(".week").css("width",wid);

  });
  //$( ".block" ).animate({ "left": "-=70px" }, "fast" );
$( "#right" ).click(function() {
  $( ".block" ).animate({ "left": "+=100px" }, "fast" );
});

$( "#left" ).click(function(){
  $( ".block" ).animate({ "left": "-=100px" }, "fast" );
});

function goCheckin(classroomId,lessonId,lessonDate){
  console.log(lessonDate);
  var para = "?classroomId="+classroomId+"&lessonDate="+lessonDate+"&searchDay={{searchDay}}"
  if(lessonId!="")
      para = para + "&lessonId="+lessonId
  document.location.href="{% url 'Teacher:lessonCheckin' %}"+para
}

function goUser(userId){
  var para = "?userId="+userId
  window.open("{% url 'User:profile' %}"+para)

}

function goClass(classId){
  var para = "?classroomId="+classId+"&searchDay={{searchDay}}"
  document.location.href="{% url 'Teacher:editClass' %}"+para
}
</script>
{% endblock %}

Teacher/templates/userCoursePlan.html
{% extends "base.html" %}
{%load filter%}
{% block content %}

<style>
  .container{background-color: #fff;}


  </style>
<div style="height:10px;"></div>
<div style="font-size:20px;padding:5px;">课程安排</div>
<div>

</div>

{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function () {
    console.log($( document ).width());
    console.log($( window ).width());
    var wid = $( document ).width();
    $(".header").css("width",wid);
    wid = $( window ).width()/3*0.9;
    $(".week").css("width",wid);

  });
  //$( ".block" ).animate({ "left": "-=70px" }, "fast" );


function goCourse(courseId){
  var para = "?courseId="+courseId
  document.location.href="{% url 'Teacher:courseEdit' %}"+para
}
</script>
{% endblock %}

Teacher/templates/userLessonSkill.html
{% extends "base.html" %}
{%load filter%}
{% block content %}

<style>
  .container{background-color: #fff;}


  </style>
<div style="height:10px;"></div>
<div style="font-size:20px;padding:5px;"><a style="font-size:14px;" href="{% url 'Teacher:lessonPlan' %}">Home></a>&nbsp;全部课程技能分布</div>
<div>
  <table  id="datatable" class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>序号</th><th>技能</th><th>使用次数</th>
    </tr>
    </thead>
    <tbody>
  {%for key,value in skill.items%}
      <tr>
        <td>{{key}}</td>
        <td>{{key|get_name:'skill'}}</td>
        <td>{{value}}</td>
      </tr>
  {%endfor%}
    </tbody>
  </table>
</div>


{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function() {
      $('#datatable').DataTable( {
      	"paging":   false,
      	"searching": false,
      	"info":false,
        "order": [[ 2, "desc" ]],
          dom: 'Bfrtip',
          buttons: [
              { extend: 'copy', text: '复制' },
              { extend: 'csv', text: '保存' },
              { extend: 'print', text: '打印' }
          ]
      });
  });
function goCourse(courseId){
  var para = "?courseId="+courseId
  document.location.href="{% url 'Teacher:courseEdit' %}"+para
}
</script>
{% endblock %}